### ISSUE TITLE
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by K-Hooshanfar** [NVlabs/MambaVision#12]
my torch version is 2.1.2 with cuda 12.1 and I have already installed the requirements, but I get the following error when creating the model (from mambavision import create_model)

File ~/miniconda3/envs/mambavision/lib/python3.10/site-packages/mamba_ssm/__init__.py:3
      1 __version__ = "1.0.1"
----> 3 from mamba_ssm.ops.selective_scan_interface import selective_scan_fn, mamba_inner_fn
      4 from mamba_ssm.modules.mamba_simple import Mamba
      5 from mamba_ssm.models.mixer_seq_simple import MambaLMHeadModel

File ~/miniconda3/envs/mambavision/lib/python3.10/site-packages/mamba_ssm/ops/selective_scan_interface.py:11
      9 from causal_conv1d import causal_conv1d_fn
     10 import causal_conv1d_cuda
---> 11 import selective_scan_cuda
     14 class SelectiveScanFn(torch.autograd.Function):
     16     @staticmethod
     17     def forward(ctx, u, delta, A, B, C, D=None, z=None, delta_bias=None, delta_softplus=False,
     18                 return_last_state=False):

ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

**Comment by K-Hooshanfar** [comment]
also i have:

- nvcc --version: 
                                                                                      
nvcc: NVIDIA (R) Cuda compiler driver                                                                                                                                   
Copyright (c) 2005-2023 NVIDIA Corporation                                                                                                                              
Built on Mon_Apr__3_17:16:06_PDT_2023                                                                                                                                   
Cuda compilation tools, release 12.1, V12.1.105                                                                                                                         
Build cuda_12.1.r12.1/compiler.32688072_0   
                                                                                                                            
-  ls /usr/local/cuda/lib64 | grep libcudart : 
                                                  
libcudart.so
libcudart.so.12
libcudart.so.12.1.105
libcudart_static.a

**Comment by ahatamiz** [comment]
Thanks ! do you have both libcudart.so.11.0 and libcudart.so.12 ? it seems that there are duplicate files for previous cuda versions that cause the discrepancy.
