### ISSUE TITLE
Installation Issues with causal-conv1d==1.0.2 on Windows

### ISSUE THREAD

**Issue by MinGiSa** [NVlabs/MambaVision#14]
When attempting to install the causal-conv1d==1.0.2 and mamba-ssm==1.0.1 modules on Windows,
the following error occurs during the causal-conv1d installation.
Is there any way to install it on Windows?

====================================================================
(mambaVision) C:\Users\USER\Desktop\Triton-for-Windows>pip install causal-conv1d==1.0.2
Collecting causal-conv1d==1.0.2
  Using cached causal_conv1d-1.0.2.tar.gz (6.4 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from causal-conv1d==1.0.2) (2.0.1+cu118)
Requirement already satisfied: packaging in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from causal-conv1d==1.0.2) (24.1)
Collecting buildtools (from causal-conv1d==1.0.2)
  Using cached buildtools-1.0.6-py3-none-any.whl
Requirement already satisfied: ninja in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from causal-conv1d==1.0.2) (1.11.1.1)
Collecting sqlalchemy (from buildtools->causal-conv1d==1.0.2)
  Using cached SQLAlchemy-2.0.31-cp310-cp310-win_amd64.whl.metadata (9.9 kB)
Collecting argparse (from buildtools->causal-conv1d==1.0.2)
  Using cached argparse-1.4.0-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting twisted (from buildtools->causal-conv1d==1.0.2)
  Using cached twisted-24.3.0-py3-none-any.whl.metadata (9.5 kB)
Collecting simplejson (from buildtools->causal-conv1d==1.0.2)
  Using cached simplejson-3.19.2-cp310-cp310-win_amd64.whl.metadata (3.2 kB)
Collecting furl (from buildtools->causal-conv1d==1.0.2)
  Using cached furl-2.1.3-py2.py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: requests in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from buildtools->causal-conv1d==1.0.2) (2.28.1)
Collecting docopt (from buildtools->causal-conv1d==1.0.2)
  Using cached docopt-0.6.2-py2.py3-none-any.whl
Collecting python-dateutil (from buildtools->causal-conv1d==1.0.2)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: jinja2 in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from buildtools->causal-conv1d==1.0.2) (3.1.4)
Collecting redo (from buildtools->causal-conv1d==1.0.2)
  Using cached redo-2.0.4-py2.py3-none-any.whl.metadata (6.0 kB)
Requirement already satisfied: filelock in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from torch->causal-conv1d==1.0.2) (3.15.4)
Requirement already satisfied: typing-extensions in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from torch->causal-conv1d==1.0.2) (4.12.2)
Requirement already satisfied: sympy in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from torch->causal-conv1d==1.0.2) (1.13.0)
Requirement already satisfied: networkx in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from torch->causal-conv1d==1.0.2) (3.3)
Collecting six>=1.8.0 (from furl->buildtools->causal-conv1d==1.0.2)
  Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting orderedmultidict>=1.0.1 (from furl->buildtools->causal-conv1d==1.0.2)
  Using cached orderedmultidict-1.0.1-py2.py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from jinja2->buildtools->causal-conv1d==1.0.2) (2.1.5)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from requests->buildtools->causal-conv1d==1.0.2) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from requests->buildtools->causal-conv1d==1.0.2) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from requests->buildtools->causal-conv1d==1.0.2) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from requests->buildtools->causal-conv1d==1.0.2) (2022.12.7)
Collecting greenlet!=0.4.17 (from sqlalchemy->buildtools->causal-conv1d==1.0.2)
  Using cached greenlet-3.0.3-cp310-cp310-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from sympy->torch->causal-conv1d==1.0.2) (1.3.0)
Collecting attrs>=21.3.0 (from twisted->buildtools->causal-conv1d==1.0.2)
  Using cached attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
Collecting automat>=0.8.0 (from twisted->buildtools->causal-conv1d==1.0.2)
  Using cached Automat-22.10.0-py2.py3-none-any.whl.metadata (1.0 kB)
Collecting constantly>=15.1 (from twisted->buildtools->causal-conv1d==1.0.2)
  Using cached constantly-23.10.4-py3-none-any.whl.metadata (1.8 kB)
Collecting hyperlink>=17.1.1 (from twisted->buildtools->causal-conv1d==1.0.2)
  Using cached hyperlink-21.0.0-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting incremental>=22.10.0 (from twisted->buildtools->causal-conv1d==1.0.2)
  Using cached incremental-22.10.0-py2.py3-none-any.whl.metadata (6.0 kB)
Collecting twisted-iocpsupport<2,>=1.0.2 (from twisted->buildtools->causal-conv1d==1.0.2)
  Using cached twisted_iocpsupport-1.0.4-cp310-cp310-win_amd64.whl.metadata (2.2 kB)
Collecting zope-interface>=5 (from twisted->buildtools->causal-conv1d==1.0.2)
  Using cached zope.interface-6.4.post2-cp310-cp310-win_amd64.whl.metadata (44 kB)
Requirement already satisfied: setuptools in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from zope-interface>=5->twisted->buildtools->causal-conv1d==1.0.2) (69.5.1)
Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Using cached furl-2.1.3-py2.py3-none-any.whl (20 kB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached redo-2.0.4-py2.py3-none-any.whl (12 kB)
Using cached simplejson-3.19.2-cp310-cp310-win_amd64.whl (75 kB)
Using cached SQLAlchemy-2.0.31-cp310-cp310-win_amd64.whl (2.1 MB)
Using cached twisted-24.3.0-py3-none-any.whl (3.2 MB)
Using cached attrs-23.2.0-py3-none-any.whl (60 kB)
Using cached Automat-22.10.0-py2.py3-none-any.whl (26 kB)
Using cached constantly-23.10.4-py3-none-any.whl (13 kB)
Using cached greenlet-3.0.3-cp310-cp310-win_amd64.whl (292 kB)
Using cached hyperlink-21.0.0-py2.py3-none-any.whl (74 kB)
Using cached incremental-22.10.0-py2.py3-none-any.whl (16 kB)
Using cached orderedmultidict-1.0.1-py2.py3-none-any.whl (11 kB)
Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Using cached twisted_iocpsupport-1.0.4-cp310-cp310-win_amd64.whl (46 kB)
Using cached zope.interface-6.4.post2-cp310-cp310-win_amd64.whl (206 kB)
Building wheels for collected packages: causal-conv1d
  Building wheel for causal-conv1d (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [110 lines of output]

      torch.__version__  = 2.0.1+cu118

      running bdist_wheel
      Guessing wheel URL:  https://github.com/Dao-AILab/causal-conv1d/releases/download/v1.0.2/causal_conv1d-1.0.2+cu118torch2.0cxx11abiFALSE-cp310-cp310-win_amd64.whl
      Precompiled wheel not found. Building from source...
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\causal_conv1d
      copying causal_conv1d\causal_conv1d_interface.py -> build\lib.win-amd64-cpython-310\causal_conv1d
      copying causal_conv1d\__init__.py -> build\lib.win-amd64-cpython-310\causal_conv1d
      running build_ext
      building 'causal_conv1d_cuda' extension
      creating C:\Users\USER\AppData\Local\Temp\pip-install-tstlfz0n\causal-conv1d_15a7d6249bc14cd6a31613d80dc5e16e\build\temp.win-amd64-cpython-310
      creating C:\Users\USER\AppData\Local\Temp\pip-install-tstlfz0n\causal-conv1d_15a7d6249bc14cd6a31613d80dc5e16e\build\temp.win-amd64-cpython-310\Release
      creating C:\Users\USER\AppData\Local\Temp\pip-install-tstlfz0n\causal-conv1d_15a7d6249bc14cd6a31613d80dc5e16e\build\temp.win-amd64-cpython-310\Release\csrc
      Emitting ninja build file C:\Users\USER\AppData\Local\Temp\pip-install-tstlfz0n\causal-conv1d_15a7d6249bc14cd6a31613d80dc5e16e\build\temp.win-amd64-cpython-310\Release\build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      ninja: error: 'C:/Users/USER/AppData/Local/Temp/pip-install-tstlfz0n/causal-conv1d_15a7d6249bc14cd6a31613d80dc5e16e/csrc/causal_conv1d.cpp', needed by 'C:/Users/USER/AppData/Local/Temp/pip-install-tstlfz0n/causal-conv1d_15a7d6249bc14cd6a31613d80dc5e16e/build/temp.win-amd64-cpython-310/Release/csrc/causal_conv1d.obj', missing and no known rule to make it
      Traceback (most recent call last):
        File "C:\Users\USER\AppData\Local\Temp\pip-install-tstlfz0n\causal-conv1d_15a7d6249bc14cd6a31613d80dc5e16e\setup.py", line 207, in run
          urllib.request.urlretrieve(wheel_url, wheel_filename)
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\urllib\request.py", line 241, in urlretrieve
          with contextlib.closing(urlopen(url, data)) as fp:
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\urllib\request.py", line 216, in urlopen
          return opener.open(url, data, timeout)
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\urllib\request.py", line 525, in open
          response = meth(req, response)
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\urllib\request.py", line 634, in http_response
          response = self.parent.error(
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\urllib\request.py", line 563, in error
          return self._call_chain(*args)
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\urllib\request.py", line 496, in _call_chain
          result = func(*args)
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\urllib\request.py", line 643, in http_error_default
          raise HTTPError(req.full_url, code, msg, hdrs, fp)
      urllib.error.HTTPError: HTTP Error 404: Not Found

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\site-packages\torch\utils\cpp_extension.py", line 1893, in _run_ninja_build
          subprocess.run(
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\subprocess.py", line 524, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\USER\AppData\Local\Temp\pip-install-tstlfz0n\causal-conv1d_15a7d6249bc14cd6a31613d80dc5e16e\setup.py", line 227, in <module>
          setup(
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\site-packages\setuptools\__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
          return run_commands(dist)
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
          dist.run_commands()
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\site-packages\setuptools\dist.py", line 967, in run_command
          super().run_command(command)
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\USER\AppData\Local\Temp\pip-install-tstlfz0n\causal-conv1d_15a7d6249bc14cd6a31613d80dc5e16e\setup.py", line 224, in run
          super().run()
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\site-packages\wheel\bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\site-packages\setuptools\dist.py", line 967, in run_command
          super().run_command(command)
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\site-packages\setuptools\dist.py", line 967, in run_command
          super().run_command(command)
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\site-packages\setuptools\command\build_ext.py", line 91, in run
          _build_ext.run(self)
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 359, in run
          self.build_extensions()
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\site-packages\torch\utils\cpp_extension.py", line 843, in build_extensions
          build_ext.build_extensions(self)
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 479, in build_extensions
          self._build_extensions_serial()
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 505, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\site-packages\setuptools\command\build_ext.py", line 252, in build_extension
          _build_ext.build_extension(self, ext)
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 560, in build_extension
          objects = self.compiler.compile(
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\site-packages\torch\utils\cpp_extension.py", line 815, in win_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\site-packages\torch\utils\cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "C:\Users\USER\anaconda3\envs\mambaVision\lib\site-packages\torch\utils\cpp_extension.py", line 1909, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for causal-conv1d
  Running setup.py clean for causal-conv1d
Failed to build causal-conv1d
ERROR: Could not build wheels for causal-conv1d, which is required to install pyproject.toml-based projects
=================================================================================

**Comment by parsakhavarinejad** [comment]
I'm experiencing the same issue

**Comment by Adam-Serghini** [comment]
I had the same issues. I ended up installing the latest version of each problematic package, and the installation worked well. However, I am now experiencing performance issues, and I don't know if it might be due to the different versions.

**Comment by MinGiSa** [comment]
@ahatamiz , The issue is still not resolved. I tried newly installing the module and followed the steps mentioned in the [link](https://github.com/state-spaces/mamba/issues/12), but the same error is occurring. My general environment is Windows 11, Python version 3.10, Triton Windows version, and Visual Studio 2019

**Comment by JoyeZLearning** [comment]
This maybe your torch version and cuda version are  not quite up to the project's requirements. For I had met the same problems with you,. when I update my version and install the package following the requirements, the error is disappeared.

**Comment by ZombaSY** [comment]
Same issue on ubuntu==20.04, torch==2.0.0

**Comment by MinGiSa** [comment]
> This maybe your torch version and cuda version are not quite up to the project's requirements. For I had met the same problems with you,. when I update my version and install the package following the requirements, the error is disappeared.

Could you please tell me about your environment?

Here's my environment:

Operating System: Windows 11
Torch Version: 2.3.1+cu118 / 2.0.1+cu118
Python Version: 3.10.0
nvcc: Cuda compilation tools, release 11.8, V11.8.89 / Build cuda_11.8.r11.8/compiler.31833905_0
NVIDIA Driver: 555.99
I'm still experiencing the issue.

**Comment by JoyeZLearning** [comment]
use cuda 12.1  
if you still meet the same problems, you can follow

git clone https://github.com/Dao-AILab/causal-conv1d.git
cd causal-conv1d
git checkout v1.1.1 # current latest version tag
CAUSAL_CONV1D_FORCE_BUILD=TRUE pip install .
cd ..
git clone https://github.com/state-spaces/mamba.git
cd mamba
git checkout v1.1.1 # current latest version tag
pip install .

**Comment by MinGiSa** [comment]
> use cuda 12.1 if you still meet the same problems, you can follow
> 
> ```
> git clone https://github.com/Dao-AILab/causal-conv1d.git
> cd causal-conv1d
> git checkout v1.1.1 # current latest version tag
> CAUSAL_CONV1D_FORCE_BUILD=TRUE pip install .
> cd ..
> git clone https://github.com/state-spaces/mamba.git
> cd mamba
> git checkout v1.1.1 # current latest version tag
> pip install .
> ```

Thank you. The installation was successful with causal-cov1d, but another issue arose with mamba_ssm.
anyway, how did you install triton?

(mambaVision) C:\Users\USER\Desktop\MambaVision\mamba>pip install .
Processing c:\users\user\desktop\mambavision\mamba
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from mamba_ssm==2.2.2) (2.3.1+cu121)
Requirement already satisfied: packaging in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from mamba_ssm==2.2.2) (24.1)
Requirement already satisfied: ninja in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from mamba_ssm==2.2.2) (1.11.1.1)
Requirement already satisfied: einops in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from mamba_ssm==2.2.2) (0.8.0)
Requirement already satisfied: triton in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from mamba_ssm==2.2.2) (2.0.0)
Collecting transformers (from mamba_ssm==2.2.2)
  Using cached transformers-4.42.4-py3-none-any.whl.metadata (43 kB)
Requirement already satisfied: filelock in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from torch->mamba_ssm==2.2.2) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from torch->mamba_ssm==2.2.2) (4.9.0)
Requirement already satisfied: sympy in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from torch->mamba_ssm==2.2.2) (1.12)
Requirement already satisfied: networkx in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from torch->mamba_ssm==2.2.2) (3.2.1)
Requirement already satisfied: jinja2 in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from torch->mamba_ssm==2.2.2) (3.1.3)
Requirement already satisfied: fsspec in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from torch->mamba_ssm==2.2.2) (2024.2.0)
Requirement already satisfied: mkl<=2021.4.0,>=2021.1.1 in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from torch->mamba_ssm==2.2.2) (2021.4.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from transformers->mamba_ssm==2.2.2) (0.23.5)
Requirement already satisfied: numpy<2.0,>=1.17 in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from transformers->mamba_ssm==2.2.2) (1.26.3)
Requirement already satisfied: pyyaml>=5.1 in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from transformers->mamba_ssm==2.2.2) (6.0.1)
Collecting regex!=2019.12.17 (from transformers->mamba_ssm==2.2.2)
  Using cached regex-2024.5.15-cp310-cp310-win_amd64.whl.metadata (41 kB)
Requirement already satisfied: requests in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from transformers->mamba_ssm==2.2.2) (2.32.3)
Requirement already satisfied: safetensors>=0.4.1 in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from transformers->mamba_ssm==2.2.2) (0.4.3)
Collecting tokenizers<0.20,>=0.19 (from transformers->mamba_ssm==2.2.2)
  Using cached tokenizers-0.19.1-cp310-none-win_amd64.whl.metadata (6.9 kB)
Requirement already satisfied: tqdm>=4.27 in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from transformers->mamba_ssm==2.2.2) (4.66.4)
Requirement already satisfied: cmake in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from triton->mamba_ssm==2.2.2) (3.30.0)
Requirement already satisfied: intel-openmp==2021.* in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from mkl<=2021.4.0,>=2021.1.1->torch->mamba_ssm==2.2.2) (2021.4.0)
Requirement already satisfied: tbb==2021.* in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from mkl<=2021.4.0,>=2021.1.1->torch->mamba_ssm==2.2.2) (2021.11.0)
Requirement already satisfied: colorama in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from tqdm>=4.27->transformers->mamba_ssm==2.2.2) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from jinja2->torch->mamba_ssm==2.2.2) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from requests->transformers->mamba_ssm==2.2.2) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from requests->transformers->mamba_ssm==2.2.2) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from requests->transformers->mamba_ssm==2.2.2) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from requests->transformers->mamba_ssm==2.2.2) (2024.7.4)
Requirement already satisfied: mpmath>=0.19 in c:\users\user\anaconda3\envs\mambavision\lib\site-packages (from sympy->torch->mamba_ssm==2.2.2) (1.3.0)
Using cached transformers-4.42.4-py3-none-any.whl (9.3 MB)
Using cached regex-2024.5.15-cp310-cp310-win_amd64.whl (268 kB)
Using cached tokenizers-0.19.1-cp310-none-win_amd64.whl (2.2 MB)
Building wheels for collected packages: mamba_ssm
  Building wheel for mamba_ssm (setup.py) ... error

**Comment by JoyeZLearning** [comment]
copy that code again, but this time only git the mamba   ：）

**Comment by MinGiSa** [comment]
> Have you finally solved the problem of mamba installation failure? @MinGiSa

nope, i failed.
