### ISSUE TITLE
Cannot DEBUG but can run when install cuda12.1 and python3.12

### ISSUE THREAD

**Issue by JoyeZLearning** [NVlabs/MambaVision#16]
```
/root/.pycharm_helpers/pydev/pydevd.py:1844: DeprecationWarning: currentThread() is deprecated, use current_thread() instead
  dummy_thread = threading.currentThread()
Connected to pydev debugger (build 211.7142.13)
Traceback (most recent call last):
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 2173, in <module>
    main()
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 2164, in main
    globals = debugger.run(setup['file'], None, None, is_module)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1395, in run
    m = save_main_module(file, 'pydevd')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_utils.py", line 43, in save_main_module
    from imp import new_module
ModuleNotFoundError: No module named 'imp'

Process finished with exit code 1

```
The program works under cuda12.1 and python 3.12, but when I try to debug some intermediate results, I keep being told I can't debug. Before I updated cuda, my python was 3.8 and cuda11.8, which was fine to debug but not to run.
Now when I update cuda to 12.1, the corresponding python version is 3.12, there is a problem that can not be debug, I do not know what is the problem.

for the 
`/root/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_utils.py`
I cannot change that since it was generated on the cloud server when python3.12 was installed, I don't seem to have permission to change it

**Comment by ahatamiz** [comment]
Hi @JoyeZLearning , thanks for the question and sorry for the late reply. I am not specifically sure what causes this issue but both cuda 12.1 and cuda 11.8 should work, provided that Pytorch version is recent and compatible. Additionally, it would help to see the logs to pinpoint the error.

**Comment by JoyeZLearning** [comment]
Thanks very much for replying my question. The codes have no errors now.
I found  my former problem was due to my Pycharm version. The 2021 version pycharm could not  match python 3.12.  :）

**Comment by ahatamiz** [comment]
This is great. Glad the issue has been resolved !
