### ISSUE TITLE
How to adapt your model on images that the resolution is not 224*224?

### ISSUE THREAD

**Issue by whu-lyh** [NVlabs/MambaVision#2]
For vit, I should interpolate the position embeddings to the desired image resolution. What do you think I should do to deal with the images that the resolution is not 224*224? Thanks.

**Comment by ahatamiz** [comment]
sure, let us address this issue via a new PR. But it would be much easier than a ViT or Swin, etc due to not relying on components such as relative position bias, etc. 

Please stay tuned.

**Comment by whu-lyh** [comment]
Oops, that's it, thank you!!

**Comment by abebe9849** [comment]
By adding the code below, I can now input any size.

``` #MambaVisionLayer 
    def forward(self, x):
        B, C, H, W = x.shape
        if self.transformer_block:
            pad_l = pad_t = 0
            pad_r = (self.window_size - W % self.window_size) % self.window_size
            pad_b = (self.window_size - H % self.window_size) % self.window_size
            
            x = F.pad(x.permute((0,2,3,1)), (0, 0, pad_l, pad_r, pad_t, pad_b)).permute((0,3,1,2))
            #print(x.shape)
            _,_,Hp, Wp = x.shape
            x = window_partition(x, self.window_size)
        for _, blk in enumerate(self.blocks):
            x = blk(x)
        if self.transformer_block:
            
            x = window_reverse(x, self.window_size, Hp, Wp)

```

**Comment by whu-lyh** [comment]
I will try this later, thanks~

**Comment by zhangjy2008327** [comment]
hello, everyone, I come cross the problem when using the mambavision,
ImportError: cannot import name '_update_default_kwargs' from 'timm.models._builder'
please take your valuable time to provide guidance when you see this message. Thank you very much

**Comment by ahatamiz** [comment]
@whu-lyh support for processing any resolution images is now added. 

Thanks.

**Comment by ahatamiz** [comment]
Thanks @zhangjy2008327  ! already addressed.
