### ISSUE TITLE
I can't find the model checkpoint

### ISSUE THREAD

**Issue by xubigboy** [NVlabs/MambaVision#35]
I can't find the model checkpoint because the web page cannot be opened. What is the solution?

**Comment by ahatamiz** [comment]
Please download here

![model](https://github.com/user-attachments/assets/d387d65a-61d2-4b2b-92de-9e0fd59436eb)

**Comment by xubigboy** [comment]
Thank you for your reply, but the web page cannot be opened after I clicked here. Is there any other download method, or if conditions permit, can you help you upload it to Google's disk? Thank you very much.
![60774682db9f3941c6bb3eede9b8f42](https://github.com/user-attachments/assets/2a778510-871b-48ed-adf3-040644f785bb)

**Comment by ahatamiz** [comment]
Hi @xubigboy : is this like a regional issue cause I have not received this complained by other users ? 

Unfortunately, we are moving away from GDrive paradigm for sharing models. But they are still available here:

https://pypi.org/project/mambavision/1.0.5/
![Screenshot from 2024-08-31 10-53-09](https://github.com/user-attachments/assets/780bde4c-16fc-4f04-941b-585c9ae3018b)


Please download before they are gone.

**Comment by xubigboy** [comment]
您好！您的来信，我已收到！祝您新年快乐，身体健康，心想事成！
