### ISSUE TITLE
About Attention Blocks

### ISSUE THREAD

**Issue by RohollahHS** [NVlabs/MambaVision#44]
Hi, Congrats for the amazing works,

Is any positional embedding used before self-attention? I couldn't find any.

Thanks

**Comment by ahatamiz** [comment]
Thanks @RohollahHS ! 

Yes, we don't use any positional embedding since the preceding Mamba-based layers implicitly encode such information.

**Comment by ahatamiz** [comment]
@RohollahHS As discussed in the paper, bidirectional scan is suboptimal for vision tasks and our macro design in MamaVision addresses the issue with integrating the self-attention blocks. That being said, we did not consider more advanced scan patterns as our design in our work.

**Comment by RohollahHS** [comment]
Thanks, got it.
