### ISSUE TITLE
Please introduce: Which one is better in terms of running speed and feature extraction ability between mambavision and RADIO-V2.5? 

### ISSUE THREAD

**Issue by tianyi-1349** [NVlabs/MambaVision#45]
Hi, thanks for the amazing work!
Please introduce: Which one is better in terms of running speed and feature extraction ability between mambavision and RADIO-V2.5?
Looking forward to your answer!

**Comment by ahatamiz** [comment]
Hi, thanks for the question. It's recommended that you test each model based on your desired application of interest to find the right trade off.
