### ISSUE TITLE
ImportError: cannot import name '_update_default_kwargs' from 'timm.models._builder' 

### ISSUE THREAD

**Issue by zhangjy2008327** [NVlabs/MambaVision#5]
Hi, how to solve the problem in using timm lib?

**Comment by ahatamiz** [comment]
Hi @zhangjy2008327 , would you please let me know what version of timm library you are using ?

**Comment by ahatamiz** [comment]
@zhangjy2008327 Thanks for bringing this issue up. It's a mismatch with different timm library versions. I will address it shortly.
