### ISSUE TITLE
RuntimeError: CUDA error: invalid argument Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### ISSUE THREAD

**Issue by JoyeZLearning** [NVlabs/MambaVision#6]
losses.backward()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: invalid argument
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

I follow the readme, and the model can run in forward process, and debug without error. BUT when I train it ,the loss cannot backward， Is there anything I forget?  
I am looking forward sincerely

**Comment by ahatamiz** [comment]
@JoyeZLearning Thanks for bringing this to our attention. What versions of cuda and Pytorch were used in this instance ?

**Comment by JoyeZLearning** [comment]
cuda118 and torch2.0.0

**Comment by ahatamiz** [comment]
Could you please bump the torch version ? ideally  `pip install torch == 2.1.2 ` and `cuda12.1`. 

Our docker [file](https://github.com/NVlabs/MambaVision/blob/main/Dockerfile) would also address the issue in terms of resolving the mismatch.

**Comment by JoyeZLearning** [comment]
I have tried update my torch and cuda. BUT I meet new errors.
for I want to use mambavision as a backbone to do detection tasks under detectron2 framework, but when I bump my torch to 2.1.2 and cuda12.1, the detectron2 cannot work. If I donot update my torch, detectrons can work, but mambavision cannot [loss.backward()]. So I was in a dilemma.  T^T
could you share/release your mambavision code on detection tasks?
